apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: docker-project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: uday1002/frontend-img:latest
          ports:
            - containerPort: 80
